version: '3.1'

services:
  mongo:
    image: mongo:5.0.4-focal
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-db:/data/db
    networks:
      - dbnetwork

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    networks:
      - dbnetwork

  rln-chat-server:
    image: 490752553772.dkr.ecr.eu-central-1.amazonaws.com/zk-chat-api:latest
    pull_policy: always
    container_name: api
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always
    expose:
      - 8080
      - 8081
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - REDIS_CHANNEL=nodeSync
      - INTERREP_BASE_URL=https://api.thegraph.com/subgraphs/name/interrep/kovan
      - INTERREP_V2=https://api.pcd-passport.com
      - DB_CONNECTION_STRING=mongodb://mongo:27017/test
      - SERVER_PORT=8080
      - SOCKET_SERVER_PORT=8081
      - MERKLE_TREE_LEVELS=16
      - SPAM_TRESHOLD=1
      - EPOCH_ALLOWED_DELAY_THRESHOLD=100
      - INTERREP_SYNC_INTERVAL_SECONDS=20
      - RLN_IDENTIFIER=518137101
      - MESSAGES_CHANNEL=messages
      - MESSAGES_BROADCAST_CHANNEL=message-broadcast
      - UPDATES_CHANNEL=updates
    depends_on:
      - mongo
      - redis
    networks:
      - apinetwork
      - dbnetwork

  rln-chat-client:
    image: 490752553772.dkr.ecr.eu-central-1.amazonaws.com/zk-chat-client:latest
    pull_policy: always
    container_name: client
    ports:
      - "3000:3000"
    expose:
      - 3000
    restart: always
    environment:
      - PORT=3000
      - REACT_APP_SERVER_HOST=https://dev-api.zkchat.org
      - REACT_APP_SOCKET_HOST=wss://dev-api-wss.zkchat.org
      - REACT_APP_ENV=https://dev.zkchat.org
    depends_on:
      - mongo
      - redis
      - rln-chat-server
    networks:
      - apinetwork

networks:
  dbnetwork:
    driver: bridge
    internal: true
  apinetwork:
    driver: bridge
